### ISSUE TITLE
bundle luarocks modules?

### ISSUE THREAD

**Issue by retorquere** [Benjamin-Dobell/luabundler#2]
What should I add on the command line to bundle luarocks-installed bundles?

**Comment by Benjamin-Dobell** [comment]
You'll want to add any paths you with to search as [-p <path>](https://github.com/Benjamin-Dobell/luabundler#search-paths--p) arguments.

Lua itself uses the environment variable `LUA_PATH`. You can print this variable to determine what paths are configured on your system. If it's not set in your shell, you can execute `luarocks path` to print the environment variables (including `LUA_PATH`) that LuaRocks sets.

Please note that luabundler takes each individual path as a separate `-p <path>` argument, it does not accept a semicolon delimited list as one argument.
